
package sasf.jayon.clientsoap.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProductsPort", targetNamespace = "http://soapservice.jayon.sasf/springsoap/product/gen")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductsPort {


    /**
     * 
     * @param postProductRequest
     * @return
     *     returns sasf.jayon.clientsoap.wsdl.PostProductResponse
     */
    @WebMethod
    @WebResult(name = "postProductResponse", targetNamespace = "http://soapservice.jayon.sasf/springsoap/products/gen", partName = "postProductResponse")
    public PostProductResponse postProduct(
        @WebParam(name = "postProductRequest", targetNamespace = "http://soapservice.jayon.sasf/springsoap/products/gen", partName = "postProductRequest")
        PostProductRequest postProductRequest);

    /**
     * 
     * @param getProductsRequest
     * @return
     *     returns sasf.jayon.clientsoap.wsdl.GetProductsResponse
     */
    @WebMethod
    @WebResult(name = "getProductsResponse", targetNamespace = "http://soapservice.jayon.sasf/springsoap/products/gen", partName = "getProductsResponse")
    public GetProductsResponse getProducts(
        @WebParam(name = "getProductsRequest", targetNamespace = "http://soapservice.jayon.sasf/springsoap/products/gen", partName = "getProductsRequest")
        GetProductsRequest getProductsRequest);

    /**
     * 
     * @param getProductRequest
     * @return
     *     returns sasf.jayon.clientsoap.wsdl.GetProductResponse
     */
    @WebMethod
    @WebResult(name = "getProductResponse", targetNamespace = "http://soapservice.jayon.sasf/springsoap/products/gen", partName = "getProductResponse")
    public GetProductResponse getProduct(
        @WebParam(name = "getProductRequest", targetNamespace = "http://soapservice.jayon.sasf/springsoap/products/gen", partName = "getProductRequest")
        GetProductRequest getProductRequest);

}
